# Generated by Django 2.2 on 2019-04-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team_rating',
            field=models.IntegerField(default=1),
        ),
    ]
