# Generated by Django 2.2 on 2019-04-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190428_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empl_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_rating',
            new_name='rating',
        ),
    ]
