# Generated by Django 2.2 on 2019-04-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190428_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_points_average',
            new_name='points_average',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_points_per_day',
            new_name='points_per_day',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_tasks_average',
            new_name='tasks_average',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_tasks_per_day',
            new_name='tasks_per_day',
        ),
    ]
